name: Check Tree TP6
on:
  pull_request:
    branches: [ "master", "main" ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verif Arborescence
        run: php .github/scripts/verifarbre.php
