name: E2E Tests
on: [push]
jobs:
  testcafe-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Start Server
        run: php -S localhost:8080 &
      - name: Run TestCafe
        run: npx testcafe chrome:headless tests/form_test.js
