name: Action Mes Dates
on: [push]
jobs:
  job-exercice:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Afficher les fichiers AVANT checkout
        run: ls -R
      - name: 2. Recuperer le code (checkout)
        uses: actions/checkout@v4
      - name: 3. Afficher les fichiers APRES checkout
        run: ls -R
