name: PHPUnit Tests
on: [push, pull_request]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: Install Dependencies
        run: composer install

      - name: Run Tests with Coverage HTML
        run: ./vendor/bin/phpunit --coverage-html html-report

      - name: Deploy Coverage to GitHub Pages
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/mes-dates'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html-report
